### ISSUE TITLE
update

### ISSUE THREAD

**Issue by Daureion** [SleepProgger/imgur_userscripts#4]
is this still working?
I am not sure whether it's broken because of an update on imgur or if I am just incompetent

**Comment by SleepProgger** [comment]
Not sure to be honest. Which script are you trying to use ?
It is def. a possibility that they are broken.

Additionally they won't work with the current Greasemonkey version anymore as that dropped support for "old style" userscripts.
Maybe try to get it running with Tampermonkey instead, that worked for me with old scripts.

**Comment by Daureion** [comment]
The one that gives me brief statistics like a post count and stuff on imgur. 

Thanks for the info!

**Comment by SleepProgger** [comment]
Thanks for the response.
It looks like that one really won't work anymore with Greasemonkey, but still does with Tampermonkey (in FF at least).
One day i am going to fix all the old scripts, but no ETA ;)

If that script doesn't work with tampermonkey for you please let me know, as that would be an easy fix.

**Comment by ryan8374** [comment]
It looks like imgur_community_mute no longer works with _any_ script engine. I had been using it at forums.eveonline.com and at some point in the last week, it stopped working. It also appears to not be working at imgur.
Tested in Firefox 64, 39, & Waterfox 56.2.5
