### ISSUE TITLE
imgur_community_mute broken

### ISSUE THREAD

**Issue by SleepProgger** [SleepProgger/imgur_userscripts#5]
It looks like imgur_community_mute no longer works with _any_ script engine. I had been using it at forums.eveonline.com and at some point in the last week, it stopped working. It also appears to not be working at imgur.
Tested in Firefox 64, 39, & Waterfox 56.2.5

_Originally posted by @ryan8374 in https://github.com/SleepProgger/imgur_userscripts/issues/4#issuecomment-449173796_

**Comment by SleepProgger** [comment]
Thank you @ryan8374 
The script should now be working again (with tampermonkey that is).
If not please report it here.

Some fixes are a bit hackish so it might not work with different browsers.

**Comment by ryan8374** [comment]
It's now working with both Tampermonkey and Violentmonkey. 

Thank you.

**Comment by SleepProgger** [comment]
Awesome. Nice to hear
